version: '3.8'

services:
  web:
    build: .
    container_name: php-container
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on: 
      - db
    
  db:
    image: postgres
    container_name: pg-container
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment: 
      POSTGRES_PASSWORD: 1020